#!/usr/bin/node

if (isNaN(parseInt(process.argv[3]))) {
  console.log('Missing number of occurences');
} else {
	for (let counter = 0; counter <= parseInt(process.argv[3]); counter++) {
  console.log('C is fun');
}
}
